import '@ngrx/core/add/operator/select';
import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/operator/let';
import 'rxjs/add/operator/map';
import { Observable } from 'rxjs/Observable';
import { Store } from '@ngrx/store';
import { AppState, FiltersState, FilterStyle, OverlayStyle } from '../interfaces';
export declare function getFiltersState(store$: Store<AppState>): Observable<FiltersState>;
export declare function getFilterStyleValue(store$: Store<AppState>): Observable<FilterStyle>;
export declare function getOverlayStyleValue(store$: Store<AppState>): Observable<OverlayStyle>;
export declare function getContrastFilterValue(store$: Store<AppState>): Observable<number>;
export declare function getBrightnessFilterValue(store$: Store<AppState>): Observable<number>;
export declare function getSaturateFilterValue(store$: Store<AppState>): Observable<number>;
export declare function getSepiaFilterValue(store$: Store<AppState>): Observable<number>;
export declare function getGrayScaleFilterValue(store$: Store<AppState>): Observable<number>;
export declare function getInvertFilterValue(store$: Store<AppState>): Observable<number>;
export declare function getHueRotateFilterValue(store$: Store<AppState>): Observable<number>;
export declare function getBlurFilterValue(store$: Store<AppState>): Observable<number>;
export declare function getBlendFilterValue(store$: Store<AppState>): Observable<string>;
export declare function getSelectedImage(store$: Store<AppState>): Observable<string>;
export declare function getImages(store$: Store<AppState>): Observable<any>;
export declare function getError(store$: Store<AppState>): Observable<string>;
export declare function getLoading(store$: Store<AppState>): Observable<boolean>;
